### ISSUE TITLE
clim

### ISSUE THREAD

**Issue by manihyip** [drignads/PCS-PREDICTION-MULTI_STRATEGY-BOT#6]
i face with an error when clime:

Balance   Bellow 0.1, fetching claimable rounds...% 
Attempting   to claim 3 rounds...% 
[46088, 46038, 46036] |  
Restarting...%   {'code': -32601, 'message': 'the method eth_maxPriorityFeePerGas does not   exist/is not available'}

how can i solve that?

**Comment by drignads** [comment]
Sup! I believe this is due to the missing gas and gas price values on the claim function. When these values are missing, the web3 tries to calculate the values on default mode. Sometimes this throw error. You get two options, add a line to calculate the gas-gas_price values, or just add a high value for them that will cover if you try to claim 1 or N epochs

````python
def claim(epochs):
    txn = PREDICTION_CONTRACT.functions.claim(epochs).buildTransaction({
        'from': ADDRESS,
        'nonce': w3.eth.getTransactionCount(ADDRESS)
        # add 'gas':    ,
        # add 'gas_price': 

    })
    signed_txn = w3.eth.account.signTransaction(txn, private_key=PRIVATE_KEY)
    w3.eth.sendRawTransaction(signed_txn.rawTransaction)
    print(f'{w3.eth.waitForTransactionReceipt(signed_txn.hash)}')
```

**Comment by drignads** [comment]
I did not test it but I believe if you set GAS to 900000 it will be enough to claim +10 rounds/epochs

**Comment by drignads** [comment]
check new release :)
